// firstChild , lastChild , childnodes

// console.log(document.body.firstChild) // return firstchild of targeted element
// console.log(document.body.lastChild) // return lastchild of targeted element
// console.log(document.body.childNodes) // return all childs

// let a = document.body.firstChild === document.body.childNodes[0]
// let a = document.body.lastChild === document.body.childNodes[document.body.childNodes.length - 1];

// console.log(document.body.parentElement) // for parentElement
// console.log(document.head.nextElementSibling) // for next Element
// console.log(document.body.previousElementSibling) // for previous Element

// console.log(document.body.firstElementChild)
// console.log(document.body.lastElementChild)

// document.getElementById("heading").innerHTML = "hey whats app"

// document.body.firstElementChild.firstElementChild.firstElementChild.innerHTML = "It will change again"

// console.log(document.querySelectorAll("h1")[0])
// console.log(document.querySelector("h1"))

// console.log(document.getElementsByTagName("h1")[0])

// console.log(document.getElementsByClassName("ajay")[0])

// console.log(document.getElementsByName("hi"))


// matches , closet , contains

// console.log(document.body.matches(".boy")) //cheks css selector return booleans
// console.log(document.getElementsByTagName("header")[0].closest(".ajay")) //cheks css selector return element
// console.log(document.getElementById("myDIV").contains(document.getElementById("mySPAN")))

// Practice Set 7

// 1. Solution

// document.getElementsByTagName("nav")[0].firstElementChild.style.color = "red"

// 2. Solution

// tbody automatically generated by html

// 3. Solution

// document.getElementsByTagName("div")[0].firstElementChild.style.color = "green"
// document.getElementsByTagName("div")[0].lastElementChild.style.color = "green"

// 4. Solution

// document.getElementsByTagName("li")[0].style.backgroundColor = "cyan"
// document.getElementsByTagName("li")[1].style.backgroundColor = "cyan"
// document.getElementsByTagName("li")[2].style.backgroundColor = "cyan"
// document.getElementsByTagName("li")[3].style.backgroundColor = "cyan"

// for(let i = 0; i< document.getElementsByTagName("li").length - 1; i++) {
//     document.getElementsByTagName("li")[i].style.backgroundColor = "cyan";
// }


// 5. Solution

// NONE OF THIS 

